# Generated by Django 5.2.17 on 2026-09-11 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('url', models.URLField()),
                ('identifier', models.CharField(blank=True, max_length=120)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('acronym', models.CharField(blank=True, max_length=30)),
                ('external_id', models.CharField(blank=True, max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parliamentarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('civil_name', models.CharField(blank=True, max_length=180)),
                ('photo_url', models.URLField(blank=True)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('level', models.CharField(choices=[('FEDERAL', 'Câmara dos Deputados'), ('STATE', 'ALESP'), ('MUNICIPAL', 'Câmara Municipal de São Paulo')], max_length=20)),
                ('is_mock', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legislature.datasource')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parliamentarians', to='legislature.party')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=180)),
                ('parliamentarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandates', to='legislature.parliamentarian')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('presented_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Em tramitação'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado'), ('ARCHIVED', 'Arquivado')], default='IN_PROGRESS', max_length=20)),
                ('level', models.CharField(choices=[('FEDERAL', 'Câmara dos Deputados'), ('STATE', 'ALESP'), ('MUNICIPAL', 'Câmara Municipal de São Paulo')], max_length=20)),
                ('is_mock', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='legislature.parliamentarian')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legislature.datasource')),
                ('themes', models.ManyToManyField(blank=True, related_name='projects', to='legislature.theme')),
            ],
            options={
                'ordering': ['-presented_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField()),
                ('description', models.CharField(max_length=300)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legislature.datasource')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_events', to='legislature.project')),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField(unique=True)),
                ('summary', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('POLITICS', 'Política'), ('CONGRESS', 'Congresso'), ('GOVERNMENT', 'Governo'), ('STF', 'STF'), ('ELECTIONS', 'Eleições'), ('ECONOMY', 'Economia'), ('SAO_PAULO', 'São Paulo')], max_length=30)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legislature.datasource')),
                ('parliamentarians', models.ManyToManyField(blank=True, to='legislature.parliamentarian')),
                ('projects', models.ManyToManyField(blank=True, to='legislature.project')),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('level', models.CharField(choices=[('FEDERAL', 'Câmara dos Deputados'), ('STATE', 'ALESP'), ('MUNICIPAL', 'Câmara Municipal de São Paulo')], max_length=20)),
                ('projects', models.ManyToManyField(blank=True, related_name='committees', to='legislature.project')),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('voted_at', models.DateTimeField()),
                ('result', models.CharField(blank=True, max_length=120)),
                ('level', models.CharField(choices=[('FEDERAL', 'Câmara dos Deputados'), ('STATE', 'ALESP'), ('MUNICIPAL', 'Câmara Municipal de São Paulo')], max_length=20)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votings', to='legislature.project')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legislature.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('YES', 'Sim'), ('NO', 'Não'), ('ABSTENTION', 'Abstenção'), ('ABSENT', 'Ausente')], max_length=20)),
                ('parliamentarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='legislature.parliamentarian')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='legislature.voting')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('voting', 'parliamentarian'), name='unique_vote_per_parliamentarian')],
            },
        ),
    ]
