# Generated by Django 5.2.17 on 2026-09-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='external_id',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
    ]
