# Generated by Django 5.2.17 on 2026-09-11 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislature', '0002_alter_party_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='official_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=120, unique=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=240)),
                ('supplier', models.CharField(blank=True, max_length=240)),
                ('document_number', models.CharField(blank=True, max_length=120)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('document_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parliamentarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='legislature.parliamentarian')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legislature.datasource')),
            ],
            options={
                'ordering': ['-year', '-month', '-value'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('parliamentarian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legislature.parliamentarian')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legislature.project')),
                ('voting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legislature.voting')),
            ],
        ),
    ]
