# Generated by Django 5.2.17 on 2026-09-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislature', '0003_voting_official_url_expense_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_date', models.DateField(unique=True)),
                ('summary', models.TextField()),
                ('article_count', models.PositiveSmallIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-reference_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-published_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='voting',
            options={'ordering': ['-voted_at', '-id']},
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['category', '-published_at'], name='legislature_categor_27b462_idx'),
        ),
        migrations.AddIndex(
            model_name='parliamentarian',
            index=models.Index(fields=['level', 'name'], name='legislature_level_831471_idx'),
        ),
        migrations.AddIndex(
            model_name='parliamentarian',
            index=models.Index(fields=['level', 'state'], name='legislature_level_3689f7_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['level', '-presented_at'], name='legislature_level_c12b2d_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', '-presented_at'], name='legislature_status_1c9385_idx'),
        ),
        migrations.AddIndex(
            model_name='voting',
            index=models.Index(fields=['level', '-voted_at'], name='legislature_level_c0fe0c_idx'),
        ),
    ]
