# Generated by Django 5.2.17 on 2026-09-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislature', '0004_dailybrief_alter_newsarticle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parliamentarian',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='parliamentarian',
            index=models.Index(fields=['level', 'is_active', 'name'], name='legislature_level_cfa934_idx'),
        ),
    ]
