# Generated by Django 5.2.17 on 2026-09-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislature', '0005_parliamentarian_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
