# Generated by Django 5.2.17 on 2026-09-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislature', '0006_voting_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='organ',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='voting',
            name='procedure',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='voting',
            name='subject_detail',
            field=models.TextField(blank=True),
        ),
    ]
