# Generated by Django 5.2.17 on 2026-09-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislature', '0007_voting_organ_voting_procedure_voting_subject_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='full_text_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='regime',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='project',
            name='situation',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='project',
            name='type_description',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
