# Generated by Django 5.2.17 on 2026-09-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislature', '0008_project_full_text_url_project_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='text_summary',
            field=models.TextField(blank=True),
        ),
    ]
